"""Export conversations to HTML — share beautiful conversation reports.

Inspired by gsd-pi's export-html module, this module provides:
  - Export conversations to HTML files
  - Beautiful styling with themes
  - Include metadata and statistics
  - Support for code highlighting
"""
from __future__ import annotations

import html
import json
import time
from dataclasses import asdict
from pathlib import Path
from typing import Any


# HTML template
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
        }}
        .header h1 {{ font-size: 24px; margin-bottom: 10px; }}
        .header .meta {{ opacity: 0.9; font-size: 14px; }}
        .message {{
            background: white;
            border-radius: 10px;
            padding: 20px;
            margin-bottom: 15px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .message.user {{ border-left: 4px solid #667eea; }}
        .message.assistant {{ border-left: 4px solid #48bb78; }}
        .message.system {{ border-left: 4px solid #ed8936; background: #fffaf0; }}
        .message .role {{
            font-weight: bold;
            font-size: 12px;
            text-transform: uppercase;
            color: #666;
            margin-bottom: 8px;
        }}
        .message .content {{ white-space: pre-wrap; }}
        .message .timestamp {{
            font-size: 11px;
            color: #999;
            margin-top: 10px;
        }}
        pre {{
            background: #1a1a1a;
            color: #a8e6cf;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
            margin: 10px 0;
        }}
        code {{ font-family: 'Monaco', 'Menlo', monospace; font-size: 14px; }}
        .footer {{
            text-align: center;
            color: #999;
            font-size: 12px;
            margin-top: 30px;
            padding: 20px;
        }}
        .stats {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 15px;
            margin-bottom: 30px;
        }}
        .stat {{
            background: white;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .stat .value {{ font-size: 24px; font-weight: bold; color: #667eea; }}
        .stat .label {{ font-size: 12px; color: #666; margin-top: 5px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
        <div class="meta">
            Exported on {export_date}<br>
            Provider: {provider} | Model: {model}
        </div>
    </div>
    
    <div class="stats">
        <div class="stat">
            <div class="value">{total_messages}</div>
            <div class="label">Messages</div>
        </div>
        <div class="stat">
            <div class="value">{total_tokens}</div>
            <div class="label">Tokens</div>
        </div>
        <div class="stat">
            <div class="value">{duration}</div>
            <div class="label">Duration</div>
        </div>
        <div class="stat">
            <div class="value">{tool_calls}</div>
            <div class="label">Tool Calls</div>
        </div>
    </div>
    
    {messages_html}
    
    <div class="footer">
        Generated by Terminal AI Agent
    </div>
</body>
</html>"""

MESSAGE_TEMPLATE = """
<div class="message {role}">
    <div class="role">{role}</div>
    <div class="content">{content}</div>
    {timestamp_html}
</div>"""


def escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return html.escape(text)


def format_code_blocks(text: str) -> str:
    """Format code blocks in markdown to HTML."""
    # Simple code block formatting
    import re
    
    def replace_code_block(match: re.Match) -> str:
        lang = match.group(1) or ""
        code = match.group(2)
        return f'<pre><code class="language-{lang}">{escape_html(code)}</code></pre>'
    
    # Replace ```lang ... ``` blocks
    text = re.sub(r'```(\w*)\n(.*?)```', replace_code_block, text, flags=re.DOTALL)
    
    # Replace inline `code`
    text = re.sub(r'`([^`]+)`', r'<code>\1</code>', text)
    
    return text


def export_to_html(
    messages: list[dict[str, Any]],
    output_path: Path | str,
    title: str = "Conversation Export",
    provider: str = "",
    model: str = "",
    metadata: dict[str, Any] | None = None,
) -> Path:
    """Export messages to an HTML file.
    
    Args:
        messages: List of message dicts.
        output_path: Path to write the HTML file.
        title: Title for the HTML page.
        provider: Provider name.
        model: Model name.
        metadata: Additional metadata.
    
    Returns:
        Path to the created HTML file.
    """
    output_path = Path(output_path)
    
    # Calculate stats
    total_messages = len(messages)
    total_tokens = sum(
        len(m.get("content", "").split()) * 1.3
        for m in messages
        if isinstance(m.get("content"), str)
    )
    tool_calls = sum(
        1 for m in messages
        if m.get("role") == "assistant" and m.get("tool_calls")
    )
    
    # Calculate duration
    timestamps = [
        m.get("timestamp", 0)
        for m in messages
        if m.get("timestamp")
    ]
    if timestamps:
        duration_s = max(timestamps) - min(timestamps)
        if duration_s < 60:
            duration = f"{duration_s:.0f}s"
        elif duration_s < 3600:
            duration = f"{duration_s / 60:.1f}m"
        else:
            duration = f"{duration_s / 3600:.1f}h"
    else:
        duration = "N/A"
    
    # Build messages HTML
    messages_html = ""
    for msg in messages:
        role = msg.get("role", "unknown")
        content = msg.get("content", "")
        
        if isinstance(content, str):
            content = format_code_blocks(escape_html(content))
        else:
            content = str(content)
        
        timestamp = msg.get("timestamp")
        if timestamp:
            ts_str = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(timestamp))
            timestamp_html = f'<div class="timestamp">{ts_str}</div>'
        else:
            timestamp_html = ""
        
        messages_html += MESSAGE_TEMPLATE.format(
            role=role,
            content=content,
            timestamp_html=timestamp_html,
        )
    
    # Build HTML
    html_content = HTML_TEMPLATE.format(
        title=escape_html(title),
        export_date=time.strftime("%Y-%m-%d %H:%M:%S"),
        provider=escape_html(provider),
        model=escape_html(model),
        total_messages=total_messages,
        total_tokens=int(total_tokens),
        duration=duration,
        tool_calls=tool_calls,
        messages_html=messages_html,
    )
    
    # Write file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html_content, encoding="utf-8")
    
    return output_path


def export_session_to_html(
    session_data: dict[str, Any],
    output_path: Path | str,
    title: str | None = None,
) -> Path:
    """Export a session dict to HTML.
    
    Args:
        session_data: Session data with messages.
        output_path: Path to write the HTML file.
        title: Title (defaults to session ID).
    
    Returns:
        Path to the created HTML file.
    """
    messages = session_data.get("messages", [])
    info = session_data.get("info", {})
    
    if title is None:
        title = f"Session {info.get('id', 'Unknown')}"
    
    return export_to_html(
        messages=messages,
        output_path=output_path,
        title=title,
        provider=info.get("provider", ""),
        model=info.get("model", ""),
        metadata=info,
    )
